alignsize: 9
backbone: vgg16
batch_size: 1
data_augmentation: true
display_freq: 200
eval_freq: 1
gpu_id: 0
image_size:
- 256
- 256
keep_aspect_ratio: ture
lr: 0.0001
lr_decay: 0.1
lr_decay_epoch:
- 40
max_epoch: 83
num_workers: 8
reddim: 32
save_freq: 81
weight_decay: 0.0001
